# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_grpc_heartbeat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61i_grpc_heartbeat.proto\x12\x07\x61i_grpc\"r\n\x0bHeartStatus\x12\x12\n\nservice_id\x18\x01 \x01(\x04\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.ai_grpc.StatusCode\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12\n\n\x02ip\x18\x05 \x01(\t\"\x19\n\nHeartReply\x12\x0b\n\x03msg\x18\x01 \x01(\t*\'\n\nStatusCode\x12\x0c\n\x08SLEEPING\x10\x00\x12\x0b\n\x07WORKING\x10\x01\x32G\n\x0b\x41IGprcHeart\x12\x38\n\tHeartBeat\x12\x14.ai_grpc.HeartStatus\x1a\x13.ai_grpc.HeartReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_grpc_heartbeat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSCODE._serialized_start=179
  _STATUSCODE._serialized_end=218
  _HEARTSTATUS._serialized_start=36
  _HEARTSTATUS._serialized_end=150
  _HEARTREPLY._serialized_start=152
  _HEARTREPLY._serialized_end=177
  _AIGPRCHEART._serialized_start=220
  _AIGPRCHEART._serialized_end=291
# @@protoc_insertion_point(module_scope)
