# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_grpc_heartbeat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ai_grpc_heartbeat.proto',
  package='ai_grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x61i_grpc_heartbeat.proto\x12\x07\x61i_grpc\"r\n\x0bHeartStatus\x12\x12\n\nservice_id\x18\x01 \x01(\x04\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.ai_grpc.StatusCode\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12\n\n\x02ip\x18\x05 \x01(\t\"\x19\n\nHeartReply\x12\x0b\n\x03msg\x18\x01 \x01(\t*\'\n\nStatusCode\x12\x0c\n\x08SLEEPING\x10\x00\x12\x0b\n\x07WORKING\x10\x01\x32G\n\x0b\x41IGprcHeart\x12\x38\n\tHeartBeat\x12\x14.ai_grpc.HeartStatus\x1a\x13.ai_grpc.HeartReply\"\x00\x62\x06proto3'
)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='ai_grpc.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SLEEPING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WORKING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=179,
  serialized_end=218,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
SLEEPING = 0
WORKING = 1



_HEARTSTATUS = _descriptor.Descriptor(
  name='HeartStatus',
  full_name='ai_grpc.HeartStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_id', full_name='ai_grpc.HeartStatus.service_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='ai_grpc.HeartStatus.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ai_grpc.HeartStatus.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='ai_grpc.HeartStatus.msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='ai_grpc.HeartStatus.ip', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=150,
)


_HEARTREPLY = _descriptor.Descriptor(
  name='HeartReply',
  full_name='ai_grpc.HeartReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='ai_grpc.HeartReply.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=177,
)

_HEARTSTATUS.fields_by_name['status'].enum_type = _STATUSCODE
DESCRIPTOR.message_types_by_name['HeartStatus'] = _HEARTSTATUS
DESCRIPTOR.message_types_by_name['HeartReply'] = _HEARTREPLY
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartStatus = _reflection.GeneratedProtocolMessageType('HeartStatus', (_message.Message,), {
  'DESCRIPTOR' : _HEARTSTATUS,
  '__module__' : 'ai_grpc_heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:ai_grpc.HeartStatus)
  })
_sym_db.RegisterMessage(HeartStatus)

HeartReply = _reflection.GeneratedProtocolMessageType('HeartReply', (_message.Message,), {
  'DESCRIPTOR' : _HEARTREPLY,
  '__module__' : 'ai_grpc_heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:ai_grpc.HeartReply)
  })
_sym_db.RegisterMessage(HeartReply)



_AIGPRCHEART = _descriptor.ServiceDescriptor(
  name='AIGprcHeart',
  full_name='ai_grpc.AIGprcHeart',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=220,
  serialized_end=291,
  methods=[
  _descriptor.MethodDescriptor(
    name='HeartBeat',
    full_name='ai_grpc.AIGprcHeart.HeartBeat',
    index=0,
    containing_service=None,
    input_type=_HEARTSTATUS,
    output_type=_HEARTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIGPRCHEART)

DESCRIPTOR.services_by_name['AIGprcHeart'] = _AIGPRCHEART

# @@protoc_insertion_point(module_scope)
