# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai_grpc_heartbeat_pb2 as ai__grpc__heartbeat__pb2


class AIGprcHeartStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HeartBeat = channel.unary_unary(
                '/ai_grpc.AIGprcHeart/HeartBeat',
                request_serializer=ai__grpc__heartbeat__pb2.HeartStatus.SerializeToString,
                response_deserializer=ai__grpc__heartbeat__pb2.HeartReply.FromString,
                )


class AIGprcHeartServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HeartBeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIGprcHeartServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HeartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartBeat,
                    request_deserializer=ai__grpc__heartbeat__pb2.HeartStatus.FromString,
                    response_serializer=ai__grpc__heartbeat__pb2.HeartReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_grpc.AIGprcHeart', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIGprcHeart(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HeartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_grpc.AIGprcHeart/HeartBeat',
            ai__grpc__heartbeat__pb2.HeartStatus.SerializeToString,
            ai__grpc__heartbeat__pb2.HeartReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
