# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_grpc_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61i_grpc_service.proto\x12\x07\x61i_grpc\"?\n\x0bTaskRequest\x12#\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x13.ai_grpc.ActionCode\x12\x0b\n\x03msg\x18\x02 \x01(\t\"0\n\tTaskReply\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x15.ai_grpc.ResponseCode*\x19\n\nActionCode\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00*!\n\x0cResponseCode\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45rror\x10\x01\x32K\n\x11\x41IGprcTaskService\x12\x36\n\x08SendTask\x12\x14.ai_grpc.TaskRequest\x1a\x12.ai_grpc.TaskReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_grpc_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONCODE._serialized_start=149
  _ACTIONCODE._serialized_end=174
  _RESPONSECODE._serialized_start=176
  _RESPONSECODE._serialized_end=209
  _TASKREQUEST._serialized_start=34
  _TASKREQUEST._serialized_end=97
  _TASKREPLY._serialized_start=99
  _TASKREPLY._serialized_end=147
  _AIGPRCTASKSERVICE._serialized_start=211
  _AIGPRCTASKSERVICE._serialized_end=286
# @@protoc_insertion_point(module_scope)
